### ISSUE TITLE
Switch the "Connect with us" footer buttons to redirect to the proper websites.

### ISSUE THREAD

**Issue by dayvidwang** [acm-ucsb/acm-ucsb#22]
<img width="338" alt="image" src="https://github.com/user-attachments/assets/db1bb8f2-5108-4742-9185-84e743e86ee7">

The 'Instagram', 'Link', and 'Discord' buttons above currently link to a youtube video. They should redirect to the following links instead.

Instagram: https://www.instagram.com/acm.ucsb

Linktree: https://linktr.ee/acm_ucsb

Discord: https://discord.com/invite/p6rcUUjWaU

**Acceptance Criteria:**
Instagram Button: Must redirect to [Instagram](https://www.instagram.com/acm.ucsb) and open in a new tab.
Link Button: Must redirect to [Linktree](https://linktr.ee/acm_ucsb) and open in a new tab.
Discord Button: Must redirect to [Discord](https://discord.com/invite/p6rcUUjWaU) and open in a new tab.
Ensure all links function correctly without errors.

**Comment by smmzhu** [comment]
#32 PR to close out

**Comment by smmzhu** [comment]
finished in #32
