### ISSUE TITLE
Beautify Event Cards and Connect with Google Sheets "Database"

### ISSUE THREAD

**Issue by rohankumar2025** [acm-ucsb/acm-ucsb#25]
- Improve UI for events on bottom of landing page
- Should also be able to work for 'no events'
- Connect to google sheets for easy write/read access with all founders

**Comment by smmzhu** [comment]
I'd probably suggest break this up into two tickets — google sheets integration is considerably more annoying and is a backend task anyway

**Comment by dayvidwang** [comment]
relevant and cool read: https://www.levels.fyi/blog/scaling-to-millions-with-google-sheets.html
